
spring:
   profiles: dev
   datasource:
      testWhileIdle: true
      show-sql: true
      url: jdbc:mysql:///mediatheque_dev
      username: mediatheque_dev
      password: 
      driver-class-name: com.mysql.jdbc.Driver 
   jpa:
      hibernate:
         database: mediatheque_dev
         naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
         dialect: org.hibernate.dialect.MySQL5Dialect
         show-sql: true
         ddl-auto: update
   resources:
      static-locations: /Volumes/External Media/cacheMediatheque/
   mail:
     host: 
     port: 
     username: 
     password: 
     debug: true
     regexValidation: ^[0-9a-zA-Z.-]+@[A-Za-z]+.[A-Za-z]+$
     properties:
        mail:
           smtp:
              auth: true
              startttls:
                 enable: true
                 required: true
   
server:
   address: 127.0.0.1
   port: 8989

mediatheque:
   downloadPath: D:\Programmation\Workspace\UIMediatheque\dowload
   mailSettings: mail.properties
---

spring:
   profiles: dev-external
   datasource:
      testWhileIdle: true
      show-sql: true
      url: jdbc:mysql:///mediatheque_dev
      username: 
      password: 
      driver-class-name: com.mysql.jdbc.Driver  
      driverClassName: com.mysql.jdbc.Driver  
   jpa:
      hibernate:
         database: mediatheque_dev
         naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
         dialect: org.hibernate.dialect.MySQL5Dialect
         show-sql: true
         ddl-auto: update
   mail:
     host: 
     port: 587
     username:
     password: 
     debug: true
     properties:
        mail:
           smtp:
              auth: true
              startttls:
                 enable: true
                 required: true          
server:
   address: 127.0.0.1
   port: 8989
   
mediatheque:
   downloadPath: /varsoft/mediatheque/download

---

spring:
   profiles: dev-pc
   datasource:
      url: jdbc:mysql:///
      username: 
      password: 
      driverClassName: com.mysql.jdbc.Driver
   jpa:
      hibernate:
         naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
         dialect: org.hibernate.dialect.MySQL5Dialect
         show-sql: true
         ddl-auto: update
         globally_quoted_identifiers: true
  
server:
   address: localhost
   port: 8989
   
---
   
spring:
   profiles: prod
server:
   address: 127.0.0.0
   port: 8989
   
--- 

spring:
   profiles: dev-pc-local
   datasource:
      url: jdbc:mysql://localhost/
      username: 
      password: 
      driverClassName: com.mysql.jdbc.Driver
   jpa:
      hibernate:
         naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
         dialect: org.hibernate.dialect.MySQL5Dialect
         show-sql: true
         ddl-auto: update
         globally_quoted_identifiers: true
  
server:
   address: localhost
   port: 8989