spring:
  profiles:
    active: dev
    
---

spring:
   profiles: dev
   datasource:
      testWhileIdle: true
      show-sql: true
      url: jdbc:mysql://192.168.1.23/mediatheque_dev
      username: mediatheque_dev
      password: 3ZJj3sEEbdxJt8Xx
      driver-class-name: com.mysql.jdbc.Driver  
   jpa:
      hibernate:
         database: mediatheque_dev
         naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
         dialect: org.hibernate.dialect.MySQL5Dialect
         show-sql: true
         ddl-auto: update
        
server:
   address: 127.0.0.1
   port: 8989
   
---

logging.level: debug

spring:
   profiles: dev-pc
   datasource:
      url: jdbc:mysql://192.168.1.23/mediathequedev
      username: mediathequedev
      password: mediathequedev
      driverClassName: com.mysql.jdbc.Driver
   jpa:
      hibernate:
         naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
         dialect: org.hibernate.dialect.MySQL5Dialect
         show-sql: true
         ddl-auto: update
         globally_quoted_identifiers: true
  
server:
   address: localhost
   port: 8989
   
---
   
spring:
   profiles: prod
server:
   address: 127.0.0.0
   port: 8989
   
--- 

spring:
   profiles: dev-pc-local
   datasource:
      url: jdbc:mysql://localhost/mediatheque_dev
      username: mediathequedev
      password: mediathequedev
      driverClassName: com.mysql.jdbc.Driver
   jpa:
      hibernate:
         naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
         dialect: org.hibernate.dialect.MySQL5Dialect
         show-sql: true
         ddl-auto: update
         globally_quoted_identifiers: true
  
server:
   address: localhost
   port: 8989